[package]
name = "rust_study"
version = "0.1.0"
authors = ["ehlxr <ehlxr.me@gmail.com>"]
edition = "2018"

[dependencies]
# hello_macro = { path = "../hello_macro" }
# hello_macro_derive = { path = "../hello_macro/hello_macro_derive" }